apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
    labels:
        app: simple
spec:
    selector:
        matchLabels:
            app: simple
    replicas: 3
    template:
        metadata:
            labels:
                app: simple
        spec:
            containers:
            -   name: simple
                image: oneeyedsunday/k8_playground:server
                # imagePullPolicy: IfNotPresent
                ports:
                -   name: server-service
                    containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: server-service
spec:
    selector:
        app: simple
    ports:
    -   port: 3000
        targetPort: server-service