apiVersion: v1
kind: Pod
metadata:
  name: basic-comms
  labels:
    app: basic-comms
spec:
  containers:
    - name: basic-comms
      image: oneeyedsunday/simple-server:0.0.1
      imagePullPolicy: Never
      ports:
      - name: basic-comms
        containerPort: 3000
      # command: [ "nutcracker", "-c", "/etc/config/nutcracker.yml", "-v", "7", "-s", "6222" ]

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: basic-comms-sidecar
#   # labels:
#   #   app: basic-comms
# spec:
#   containers:
#     - name: ubuntu
#       image: oneeyedsunday/redis-cli:bionic
#       imagePullPolicy: Never
---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#     name: basic-comms-deployment
#     labels:
#         app: basic-comms
# spec:
#     selector:
#         matchLabels:
#             app: basic-comms
#     replicas: 3
#     template:
#         metadata:
#             labels:
#                 app: basic-comms
#         spec: {}

---
apiVersion: v1
kind: Service
metadata:
    name: basic-comms-service
spec:
    type: NodePort
    selector:
        app: basic-comms
    ports:
    -   port: 8080
        targetPort: basic-comm